### ISSUE TITLE
Working with the Qubes GPG client wrapper.

### ISSUE THREAD

**Issue by BorisKourt** [mozilla/sops#101]
I have a Qubes OS setup that follows this GPG practice: https://www.qubes-os.org/doc/split-gpg/

The solution for cross VM communication relies on their `qubes-gpg-client-wrapper`. Which works appropriately with git and enigmail. 

Is it possible for me to configure which GPG sops should point to? I have not been able to find this in the documentation provided.

If not, is there another way for me to make these work together? So far I tested using aliases, but it didn't seem work.

Thank you!

**Comment by autrilla** [comment]
In short, no. Currently sops simply calls whichever `gpg` binary it finds in `PATH`, so that will be GNUPG, most likely. Aliases won't work as sops (correctly) doesn't use a shell to run pgp. There are a few possible solutions:

- Link `qubes-gpg-client-wrapper` to some `gpg` and add the directory where that binary lives to `PATH` so that it's found before GNU's one.
- Slightly more desirable, file a PR so that instead of using `gpg`, we can use any other binary name, so that anything with `gpg`'s interface works.

**Comment by BorisKourt** [comment]
Question about implementation:

I set the default GPG binary and pulled the value from an environment variable (if one exists). Now I am left with the decision of how to pass this to the functions that use GPG. 

I was about to pass through as a parameter. But that is introducing quite a bit of clutter, as I have to 'thread' it through parent functions. 

I am not seeing you use much global state so I assume that is not a good direction.

I am also seeing the `tree` structure that I could use to pass the GPG path. But I am not sure if that is part of the final text output or not. It feels like the cleanest direction, but I am 100% unfamiliar with the code-base so just want to check if that's the case.

Thanks

**Comment by autrilla** [comment]
`tree` is indeed part of the final output. I would personally just have a GPG_BINARY_NAME global variable that's set to os.environ.get('GPG_BINARY_NAME', 'gpg') or something like that. There's currently no abstraction for configurations at all, so that's as good as we can get without doing major structural changes (which are coming with the new go version).

**Comment by BorisKourt** [comment]
Please take a look and tell me if there is anything you need changed.
