### ISSUE TITLE
Problem with building the alpine container in circle

### ISSUE THREAD

**Issue by ajvb** [mozilla/sops#1022]
https://app.circleci.com/pipelines/github/mozilla/sops/128/workflows/64607008-01d6-4551-9bd0-b1181fdb2f40/jobs/431

**Comment by FnTm** [comment]
@ajvb looks like an addition instead of a change snuck into the Alpine Dockerfile update recently: https://github.com/mozilla/sops/commit/dc2267e3721a1037895050f4fd02974a31692ded#diff-f865864730d7062c04cc13b1b85ba03ed5dbef3fa02fcb50b87d9117d0af1f4eR2 . My guess is that this is what is breaking the build.

**Comment by ajvb** [comment]
Fixed by #1025
