### ISSUE TITLE
sops ignores --extract flag if it is after the -d flag

### ISSUE THREAD

**Issue by jrhoward** [mozilla/sops#198]
I am using 2.0.7

when executing the decrypt option sops ignores the --extract flag if it is after the -d command 

eg:

with the secret.yaml file:

```
hello: world
goodbye: cruel world
```
the following command returns all values decrypted:

`sops -d secret.yaml --extract "['hello']" `

The following command returns only the value of hello as expected:

`sops --extract "['hello']" -d secret.yaml  `

**Comment by autrilla** [comment]
Unfortunately this is a limitation with the command line argument library we use. Since the `-d` flag doesn't take an argument, `secret.yaml` is considered the first "argument" and not "flag" in both cases. So in the first case, `secret.yaml` is the first argument, `--extract` the second, and `['hello']` the third. In the second case, --extract is a string flag, with `['hello']` as value, `-d` is also a flag, and `secret.yaml` is the first argument.

SOPS will always use the first "argument" as the input file. As a rule of thumb, the file name should always be last. This breaks compatibility with the Python version, unfortunately.

**Comment by jrhoward** [comment]
thanks for the quick response :]
