### ISSUE TITLE
Consider making packages internal

### ISSUE THREAD

**Issue by autrilla** [mozilla/sops#232]
Currently basically all of our code is exported to external users, which makes making breaking changes hard. Here's our exported name counts:

**12 Structs**
Obtained with `go list go.mozilla.org/sops/... | grep -v "vendor" | xargs -I {} godoc {} | grep "type .* struct" | wc -l`

**56 Functions**
Obtained with `go list go.mozilla.org/sops/... | grep -v "vendor" | xargs -I {} godoc {} | grep "func " | grep -v "_m" | wc -l`

**3 Interfaces**
Obtained with `go list go.mozilla.org/sops/... | grep -v "vendor" | xargs -I {} godoc {} | grep "type .* interface" | wc -l`

When using SOPS as a library, users shouldn't be concerned with any of the "internal" packages such as `aes`, `kms`, `gpg`, `yaml`, `json`. We should work on defining an exported API that we keep stable, like that on the `decrypt` package. Perhaps the API provided by `decrypt` is all external users need.

**Comment by jvehent** [comment]
> Perhaps the API provided by decrypt is all external users need.

It's all I need, and I haven't seen requests from other users of sops, so without data it's hard to define what a stable api should expose. I'm generally against abstraction layers because they reduce flexibility. `decrypt` works because it wraps several operations that are annoying to repeat in every program that uses sops, but I wouldn't make it a rule to restrict usage to it.

**Comment by autrilla** [comment]
I think we should keep going forward by noting in the documentation that only the `decrypt` package is expected to have a stable API and not making any packages internal so that people can use 'internal' APIs at their own risk.
