### ISSUE TITLE
Silence logging by default

### ISSUE THREAD

**Issue by jvehent** [mozilla/sops#306]
Sops should not output any logging by default, and provide that options under a `-v` option.

**Comment by autrilla** [comment]
Not even errors and warnings? I suppose what you want is to hide the info
level by default

**Comment by jvehent** [comment]
Well, it depends what you call errors and warning. If a file has 4 master keys, three fails but the fourth succeeds, then we shouldn't have any warning. If all four fail, we should warn and invite the user to run again with logging activated. This is similar to what `ssh` does.

**Comment by deed02392** [comment]
I just implemented the `decrypt` package yesterday, and whilst it works great, it would be nice if I could suppress the info level logging output because this has an effect on the UX.

**Comment by autrilla** [comment]
This was fixed in #307

**Comment by deed02392** [comment]
@autrilla I `go get`d yesterday, any idea why it still outputs for me?

**Comment by autrilla** [comment]
Well, you might have to set the log level just like the `sops` command does: https://github.com/mozilla/sops/blob/9d6a8d0e2101d8a00a5e69491766976147421bb1/cmd/sops/main.go#L357

**Comment by deed02392** [comment]
@autrilla I think the package that I `go get`d (from go.mozilla.org) doesn't reflect what is here on Github, because in the log entry it even says that the level is info, which you adjusted to warn in your #307 commit.

**Comment by autrilla** [comment]
Did you use go get -u?

**Comment by deed02392** [comment]
Thanks, that did it. What happened, then? `go get` fetched an archive of the package using a version that was cached rather than getting the latest one automatically?

**Comment by autrilla** [comment]
See
https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies

**Comment by deed02392** [comment]
@autrilla What I was wondering was what is the difference between `go get foo.bar` and `go get -u foo.bar` when you have _never_ `go get`'d something in the first place. However: I am actually still getting the INFO logging output even after doing `go get -u go.mozilla.org/sops and /sops/decrypt` and rebuilding my own `main.go`.

```
PS C:\Users\George\go\src\testing> .\main.exe
[PGP]    INFO[0001] Decryption failed                             fingerprint=D226738509C8A807
```

```
George@GH5520 /cygdrive/c/Users/George/go/src/testing
$ ./main.exe
[PGP]    time="2018-03-27T14:55:15+02:00" level=info msg="Decryption failed" fingerprint=D226738509C8A807
```

**Comment by autrilla** [comment]
There is no difference. But go.mozilla.org/sops was certainly present in your computer, so using -u does matter then. As to why you're getting the logging output... I don't know. I don't get it on my computer.

**Comment by deed02392** [comment]
Thanks for your continued help. It was only present because I `go get`'d it yesterday. It must have already been up-to-date, hence why I still have the issue after doing a `go get -u`. 

Anyway, can you share with me your test harness for using the `decrypt` package where you don't get the log output? Here is mine: https://gist.github.com/deed02392/91095356a69fad0a64fbf9e291efd18f 

I tried to override the `loglevel` but because you have vendored logrus, I cannot access your `logrus.WarnLevel` in order to change it to Warn (uncommented code causes error: `main.go:9:8: use of vendored package not allowed`).

**Comment by autrilla** [comment]
My test case is simply:

```go
package main

import (
	"fmt"

	"github.com/sirupsen/logrus"

	"go.mozilla.org/sops/decrypt"
	"go.mozilla.org/sops/logging"
)

func main() {
	logging.SetLevel(logrus.WarnLevel)
	result, err := decrypt.File("foo.yaml", "yaml")
	fmt.Println(result)
	fmt.Println(err)
}
```

It's inside the sops namespace, that's why I'm able to use logrus.WarnLevel. I suppose sops should reexport all logrus log levels to accomodate this use case...

**Comment by deed02392** [comment]
Yeah, that explains why it works for you. Is it possible for you to set the logging level to WarnLevel in the decrypt package, possibly as well as re-exporting logrus. This would be in line with what this issue was initially referring to (default info logging enabled).

**Comment by autrilla** [comment]
I don't have time to do that right now, but we would definitely take a PR
does that!

**Comment by deed02392** [comment]
@autrilla How about a PR that sets the default log level within `logging/logging.go`? I assume logrus defaults to the info level, so if we override it when we're setting up logging in `sops`, we don't depend on doing argument parsing like we are right now?

**Comment by autrilla** [comment]
I'm okay with setting the default level to warn as long as it's still
possible to override the default both when using it as a library and when
using the `sops` command.

**Comment by deed02392** [comment]
It won't be _still_ possible to override when it is used as a library, because it is not currently possible and I don't have enough Go knowledge to do what is necessary to enable that by re-exposing `logrus` so consumers can import `sops/logging` and then call `logging.SetLevel()`.

But the one line code change I have made locally is `log.SetLevel(logrus.WarnLevel)` on line 28 of `logging/logging.go`. This just means newly created `logrus` instances are defaulted to `WarnLevel`. They get overwritten still by SetLevel because that iterates over all the loggers and calls `SetLevel` again.

Is this approach OK with you?

**Comment by deed02392** [comment]
Alternatively @autrilla I believe you could unvendor `logrus`. I think this would then allow anyone access to `logrus` by importing it themselves and then the types will match because they will be provided locally.
