### ISSUE TITLE
Binary input starting with a double quote not handled properly

### ISSUE THREAD

**Issue by rcleere** [mozilla/sops#334]
I am trying to encrypt a plain text file but get `Error dumping file: No binary data found in tree` when trying to decrypt the file. The file I am trying to encrypt looks like the following:

`"text1" "text2"`

I do force `--input-type binary` and `--output-type json`. I have tried a few variations and most work for example, the following file inputs work: 
`"text1`
`"text1"`
`""`
`"" "`

But the following combinations result in the error because the resulting json does not have a `data` key:
`"" ""`
```
""
""
```
`"text1" "text2"`

This is how I am testing:
`$ sops -e --input-type binary --output-type json --gcp-kms <kms_location> --verbose -i testfile`

Thanks

**Comment by autrilla** [comment]
Thanks for the bug report.

This is both a bug in the JSON store and bad design of the store interface. When we load a binary file, we basically try and load it with the JSON store first to see if it's already encrypted, and check if the JSON store returns any errors. At the point of loading, the binary store does not know whether it's loading an encrypted or unencrypted file. This is a design error. In these cases, the JSON store does not return any errors, because it sees `"" ""` (and others) as a valid JSON file (it shouldn't). Because it doesn't return any errors, the binary store just returns what the JSON store returns. The JSON store reads `"" ""` as "no data", so that's what's returned. For this reason, you encrypted file is actually empty, and then decrypting doesn't work.

So, to fix this, either:

1. Redesign the Store interface and make it aware of whether it's loading/emitting an encrypted or unencrypted file
2. Make the JSON store return an error when presented with malformed input such as these examples.

(Ideally both 😉 )
