### ISSUE TITLE
Using \\ in json keys is not handled

### ISSUE THREAD

**Issue by ddelbondio** [mozilla/sops#356]
### Sops version
sops 3.0.5 (latest)

### Problem
Using escapes in json keys are not handled and produce unexpected behaviour.  
Trying to save a file with following content causes `Could not marshal tree: Error marshaling to json: invalid character 'd' in string escape code`
```json
{
	"key\\dummy": "value",
}
```
---
Additionally, using a file like this:
```json
{
	"key\\\\dummy": "value",
}
```
produces any encrypted file like:
```
{
	"test\\dummy": "...",
	"sops": {...}
}
```
Trying to open this file then causes `Error decrypting tree: Error walking tree: Could not decrypt value: Could not decrypt with AES_GCM: cipher: message authentication failed`

**Comment by ajvb** [comment]
This is caused by sops decoding the json to encrypt the leaf nodes and then encoding it. So when it is decoded `"key\\dummy"` becomes `"key\dummy"`, then when trying to encode it to output the end result, it errors on encoded the key `"key\dummy"`, which is to be expected.

Looking into a fix, but wanted to drop this in here just in case someone wants to work on this immediately.

**Comment by jamsi** [comment]
Hi folks, I'm getting this error regardless of which SOPS version I have. I'm trying to edit an existing file to add some environment variables and receive "Error decrypting tree: Error walking tree: Could not decrypt value: Could not decrypt with AES_GCM: cipher: message authentication failed"

I've tried versions 3.0.3, 3.1.1 and 3.5.0 - is there anything else I can try to decrypt this file?

**Comment by ajvb** [comment]
@jamsi You can pass `--ignore-mac` as an arg to sops to ignore the MAC, but this should not be used as a long term fix. I'd try decrypting with `--ignore-mac` and re-encrypting and seeing if you can decrypt the new version. If you cannot, then create a new issue and we can debug.

**Comment by autrilla** [comment]
I don't think `--ignore-mac` will help, since that only affects the MAC `sops` computes on the entire file tree, whereas the error above refers to a single value in the tree.

The AAD passed here:

https://github.com/mozilla/sops/blob/83a354e92fd5d0be1d5bdcfe7cf0b7f68f954ed9/sops.go#L404

Is the culprit AFAICT.

Perhaps adding additional backslashes to whatever keys in your file have escaped stuff could work. Seems a bit hacky though.

@jamsi as a very last resort scenario, you could try to recover the file with the Python version of SOPS (so 1.x versions). It's still available on PyPI (`pip install sops`) and on the python-sops branch in this repo. Maybe try 2.x too.

**Comment by jamsi** [comment]
Thanks for the assistance. Unfortunately the python version didn't work (see error below) and neither did the ignore-mac. I'll have to recreate this secrets file I think.

```INFO: the data key on this document is over 6 months old. Considering rotating it with $ sops -r <file>
Traceback (most recent call last):
  File "/usr/local/bin/sops", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sops/__init__.py", line 309, in main
    ignoreMac=args.ignore_mac)
  File "/usr/local/lib/python2.7/site-packages/sops/__init__.py", line 836, in walk_and_decrypt
    unencrypted=unencrypted_branch)
  File "/usr/local/lib/python2.7/site-packages/sops/__init__.py", line 847, in walk_and_decrypt
    unencrypted=unencrypted_branch)
  File "/usr/local/lib/python2.7/site-packages/sops/__init__.py", line 917, in decrypt
    cleartext = decryptor.update(enc_value) + decryptor.finalize()
  File "/usr/local/lib/python2.7/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 198, in finalize
    data = self._ctx.finalize()
  File "/usr/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 170, in finalize
    raise InvalidTag
cryptography.exceptions.InvalidTag```

**Comment by onedr0p** [comment]
I ran into this today too, luckily I had a backup of my secrets so I could just regenerate the file with sops.
