### ISSUE TITLE
[Question] Encrypt-only workflow?

### ISSUE THREAD

**Issue by carlpett** [mozilla/sops#359]
Hi!
Is it possible to have a workflow where people could add and edit content without having access to decrypt? We have a shared repo for "infrastructure secrets" which all teams should be able to contribute new secrets to, but we don't necessarily want them able to read all existing secrets.

I'd imagine that when editing an existing file and not having access to decryption capabilities, you'd see existing values "as-is", that is `"my-secret-username": "ENC[AES256_GCM,data:Zihc...`. Possibly there'd be some complexity involved here to ensure such data is not double-encrypted...

Would this be possible and desirable? Are there better workflows for this scenario?

**Comment by jvehent** [comment]
It's not possible in existing files with the current cryptographic protocol because documents are encrypted and decrypted with a symmetric data key generated on document creation. If you have access to the data key, you can thus do both.

Theoretically, you could implement something like this by allowing untrusted users to call the "Encrypt" KMS function via an IAM policy, and only allow trusted users to call both the Encrypt and Decrypt KMS. Those untrusted user could then create new files with their secrets (since that uses kms-encrypt only), but would never be able to reread those files ever again (because that requires kms-decrypt). I think it's of limited value and would have bad ergonomy, but maybe it addresses your needs.

My preferred approach is to have untrusted users send those secret files to trusted users who have access to sops keys. I like using [magic wormhole](https://github.com/warner/magic-wormhole) for this.

**Comment by autrilla** [comment]
Usually people handle this by having different files for different people. I think implementing key-level granularity access control would be extremely complex.

A solution I see for this is having a directory per team/group. You then specify creation rules in `.sops.yaml` such that the people in each team have access only to their directory (based on regex path matching).

Alternatively you could give your user permission to only encrypt using a KMS key (or Azure 😉) and then have them create the file using both their PGP key and the KMS key. They'll still be able to decrypt the file because they can use the PGP key, but they won't be able to decrypt other files because they don't use their PGP key.

**Comment by carlpett** [comment]
Ok, good to know. Thanks!
Also nice tip about magic wormhole, that might work for us!

**Comment by carlpett** [comment]
Wow, quick replies here :) The per-team directory is also a nice idea, thanks!
