### ISSUE TITLE
sops not working for json array of hashes

### ISSUE THREAD

**Issue by gwilton** [mozilla/sops#39]
test.json - array of hashes (test payload)

```
[{
	"example_key": "exaaasasasasple_value",
	"example_array": [
		"example_value1",
		"example_value2"
	],
	"example_number": 1234.56789
}]
```

When using sops for encrypting test.json get the following error.

```
$ sops test.json 
temp file created at /var/folders/k6/660mymls4wbfxxh3j933wp480000gn/T/tmp4bkTf5.json
Traceback (most recent call last):
  File "/usr/local/bin/sops", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/sops/__init__.py", line 292, in main
    restore_sops=stash['sops'])
  File "/Library/Python/2.7/site-packages/sops/__init__.py", line 411, in load_file_into_tree
    tree['sops'] = restore_sops.copy()
TypeError: list indices must be integers, not unicode
```

**Comment by jvehent** [comment]
Indeed, this is not supported at all. Same with YAML arrays. The reason is sops needs a hash to store the `sops` metadata as a top-level key in the resulting document. I guess we could work around that by storing the original json data under a `data` key like we do for binary files, but that's not implemented at the time.

**Comment by jvehent** [comment]
Note that one alternative would be to treat your file as binary, by using an extensions that isn't `.json` (for example `.json.sops`)

**Comment by twolfson** [comment]
Another option might be to store SOPS metadata in a separate file (e.g. `.sopsrc`). It's not too practical if someone renames a file but it allows for the same structure in YAML/JSON.

**Comment by jvehent** [comment]
I think it's important to keep the metadata in the same file.

**Comment by jvehent** [comment]
I added documentation about json and yaml types in the readme. For now, I'll close this as WONTFIX, as it is a known limitation of sops.

**Comment by twolfson** [comment]
I think this is still an error, we prob need to detect that it's not an `instanceof dict` and serialize it as data =/

**Comment by jvehent** [comment]
If the user expects the data to be managed as JSON, we should transparently manage it as BINARY. I agree that it's an error, and returning a useful message to the user, maybe pointing to the doc, would be the right way to go about this.
Then the user can decide to either change the JSON format, or encrypt the file as BINARY.

**Comment by twolfson** [comment]
Yea, a better error message should help (e.g. documenting `--output-type`). What are your thoughts on serializing as binary and then giving a warning instead of a hard failure?

I would imagine that as a user, I would appreciate not losing changes when serialization chokes (or maybe we broaden it to any serialization errors in general).

**Comment by jvehent** [comment]
From a user interface standpoint, sops could stop the editing, tell the user that serialization as format X is not working, and ask if she wants to continue by treating the file as binary. 
That might end up being complex though, because serialization failure are also used to warn users that json/yaml files may contain invalid characters.
I want to be careful how much smartness we want to put in sops, because it's usage/maintenance complexity moving forward, but I'm not against improving the situation here.

**Comment by twolfson** [comment]
I don't full understand. Could you explain "stop the editing"?

**Comment by jvehent** [comment]
Simply paused the encryption process with a user to the message indicating that the serialization failed and proposing to continue using the binary serialization.

In editor mode, the syntax is validation post-editing and the user is invited to re-enter the edit if errors are found. https://github.com/mozilla/sops/blob/master/sops/__init__.py#L274-L287

**Comment by twolfson** [comment]
Ah, I see. Yea, providing a warning message and allowing the user to resume editing the content should work.

I think we should assume YAML unless the user specifies otherwise via `--input-type`. I agree that we don't want to overcomplicate SOPS for an edge case (e.g. providing a custom prompt and allowing us to switch input type mid-process).
