### ISSUE TITLE
Opening a path fails if it contains backslashes on Windows

### ISSUE THREAD

**Issue by ljani** [mozilla/sops#424]
Steps to reproduce:

1. Download [`sops-3.2.0.exe`](https://github.com/mozilla/sops/releases/download/3.2.0/sops-3.2.0.exe) on Windows.
2. Setup a folder structure (I'm using eg. `New-Item -Type Directory mysubdomain.github.io`)
3. Try to open a file in the directory with `sops` with a backslash as a path separator

Expected output:
My `$EDITOR` opens.

Actual output from PowerShell:
```ps
my-root ❯❯❯ sops .\mysubdomain.github.io\mysecrets.json
Could not create temporary file: open C:\Users\MYUSERNAME\AppData\Local\Temp\051921619/.\mysubdomain.github.io\mysecrets.json: The system cannot find the path specified.
```

Other cases to consider:

```ps
my-root ❯❯❯ sops $pwd\mysubdomain.github.io\mysecrets.json
Could not create temporary file: open C:\Users\MYUSERNAME\AppData\Local\Temp\863419631/C:\temp\my-root\mysubdomain.github.io\mysecrets.json: The filename, directory name, or volume label syntax is incorrect.
my-root ❯❯❯ # This works (note the forward slash):
my-root ❯❯❯ sops mysubdomain.github.io/mysecrets.json
File has not changed, exiting.
```

**Comment by autrilla** [comment]
Looks like the cause might be that we need to use `path/filepath` instead of `path` here:

https://github.com/mozilla/sops/blob/988e49994db5484b64ca72dcae10250a3ad4d49b/cmd/sops/edit.go#L157

It seems that `path` just uses `/` as a separator, which is supposed to be valid on Windows... as long as it's used for the whole path, and not mixed with `\`.

I'm not going to be on a Windows PC for a while, so it'd be good if you could try this out. Also, this is the first time I hear of someone using SOPS on Windows, so that's definitely interesting to hear 😄

**Comment by ljani** [comment]
I'm happy to try it out, if you can provide me a Windows build as I don't have a build environment for `go`.

I think Windows API (eg. [`CreateFileW`](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-createfilew)) is happy with mixed separators, but I'm not so sure about `go`. I'm totally unfamiliar with `go`.

One of the reasons I chose `sops` is that you provide a Windows binary 😄 Please do not drop it!

(Another interesting consideration was to set `$EDITOR` to eg. `C:\\Program\ Files\\Notepad++\\notepad++.exe`, because `$EDITOR` supports passing arguments to the executable as well.)

**Comment by ljani** [comment]
Tested and working with v3.5.0.
