### ISSUE TITLE
Sops requests passphrase even though passphrase is already cached

### ISSUE THREAD

**Issue by michaelgeorgeattard** [mozilla/sops#429]
I am caching my passphrase using:

`echo 'passphrase' | /usr/lib/gnupg2/gpg-preset-passphrase -c keyring`

Unfortunately `sops -d encrypted.yaml` is still requesting passphrase.
If I cancel on the prompt, decryption still happens correctly.

`gpg --decrypt` works correctly with cached passphrase.

I am using `gpg` version `2.1.18`, and `sops` version `3.2.0`.

**Comment by autrilla** [comment]
My guess is that we're trying with Go's `crypto/openpgp` first, which doesn't have access to your cached passphrase, then you're cancelling the prompt and it's falling back to the GPG binary, which does have your cached passphrase.

**Comment by michaelgeorgeattard** [comment]
Managed to fix the issue, just by creating another keypair. Closing the issue for now.

**Comment by omarashry98** [comment]
hey im getting this issue...I have my private key baked into a docker image, its imported and I cached it using gpg-preset-passphrase, I only need to do decryption so i dont need the public keys...and i cant just simple create a new keypair since these public and private keys are used for other repos...
