### ISSUE TITLE
Explain benefits of (data) key rotation

### ISSUE THREAD

**Issue by DamianFekete** [mozilla/sops#536]
https://github.com/mozilla/sops#28key-rotation states

> It is recommended to renew the data key on a regular basis. 

Excluding the case when a key is removed,

1) can you please explain what the benefits are and for which attack scenario this is recommended?
2) how often do you recommend to do this? (weekly/monthly/yearly?)

**Comment by autrilla** [comment]
I see it as a defense in depth kind of strategy. If by any means an attacker gets your data key, they'll be able to decrypt future versions of the document. Whether you think it's realistic that someone will get your data key is another matter. There definitely are ways they could get it, e.g. temporarily compromised servers with access to KMS/PGP keys.

Previously `sops` warned you if your data key was more than 6 months old IIRC, but that was removed at some point, probably because I forgot to implement it during the rewrite :). It's not easy for me to recommend

**Comment by jvehent** [comment]
The other aspect you may want to consider is former employees having access
to data keys and still being able to decrypt documents long after they are
gone, even though their KMS permissions have been removed. Rotating data
keys regularly ensures that you cannot decrypt future versions of a
document.

**Comment by DamianFekete** [comment]
Thanks @autrilla.
As I see it, in case you don't change the secrets there is no need for rotating the key and if you (seldom) change the secrets you could just rotate the data key, "just in case", right?

@jvehent, I agree, but that was included in the excluded case.

When removing the key using for e.g. `sops --rm-pgp` it may be helpful to show a warning in case a rotation wasn't specified or even doing the key rotation automatically.
