### ISSUE TITLE
Deal with special char

### ISSUE THREAD

**Issue by galindro** [mozilla/sops#628]
If the variable value has a special char like $, it isn't correctly evaluated when using SOPS with exec-env no matter if the variable value is double/single quoted in the file or in the shell execution.

Example:

```bash
$ sops -d s.env 
MYVAR='$uuhh$jjhh'

# no results are displayed at all
$ sops exec-env s.env "echo \"$MYVAR\""
$ sops exec-env s.env "echo $MYVAR"
$ sops exec-env s.env "echo '$MYVAR'"
```

**Comment by scjudd** [comment]
Hey @galindro, I'm pretty certain your problem is that your shell is going to evaluate `$MYVAR` before passing it to SOPS. What SOPS sees is this: `"echo "`.

If you run your command like so, it'll work:

```console
$ sops exec-env s.env 'echo $MYVAR'
'$uuhh$jjhh'
```

Now, if you aren't expecting the value to be wrapped in single-quotes, consider upvoting PR #622 which makes the SOPS dotenv store interpret quotes around values and values with newlines correctly. :wink:

**Comment by galindro** [comment]
Indeed It worked @scjudd . Thank you very much
