### ISSUE TITLE
Sops mac for yaml stream should be per YAML doc, not per file

### ISSUE THREAD

**Issue by derrickburns** [mozilla/sops#631]
One cannot split a YAML stream into separate documents with a MAC for the entire file.

**Comment by autrilla** [comment]
You can make the exact same argument that the YAML stream should not be splittable, reorderable, etc without warning, since that changes the semantics. It's an arbitrary choice we made, and we can't change it anymore, unfortunately. The choice we made back in the day errs on the side of security, which IMO is the right thing for a security tool to do. You can still pull out single documents with minor hassle.

**Comment by derrickburns** [comment]
Fair enough
