### ISSUE TITLE
decrypt a file get a error

### ISSUE THREAD

**Issue by huang12zheng** [mozilla/sops#794]
it maybe like #767 
---
* encrypt and decrypt, getting a error about '/Users/huangzheng/.gnupg/secring.gpg: no such file or....',
* but it is successful, if I do some gpg event.

> it make me stupid
---
# steps:
1. add fingerprints to .sops.yaml
```yaml
# .sops.yaml case1
creation_rules:
        - pgp: >-
            B513B176F005C6DC3BA87FF9F243CA4F451F3226
```
2. encrypt and decrypt
```s
3233  sops -e foo.yaml>foo.enc.yaml
3234  sops foo.enc.yaml
```
```s
sops foo.enc.yaml
Failed to get the data key required to decrypt the SOPS file.

Group 0: FAILED
  3AEC5FBBF2271FD58AB566BC757DC9A310BD5F1C: FAILED
    - | could not decrypt data key with PGP key:
      | golang.org/x/crypto/openpgp error: Could not load secring:
      | open /Users/huangzheng/.gnupg/secring.gpg: no such file or
      | directory; GPG binary error: exit status 2

Recovery failed because no master key was able to decrypt the file. In
order for SOPS to recover the file, at least one key has to be successful,
but none were.
```
> /Users/huangzheng/.gnupg/secring.gpg is no exist.
3. do some gpg event.
```s
gpg --recipient 805104533@qq.com -o foo.yaml.o -e foo.yaml
gpg --decrypt foo.yaml.o
```
```s
(base) ➜  test git:(master) ✗ gpg --recipient 805104533@qq.com -o foo.yaml.o -e foo.yaml
File 'foo.yaml.o' exists. Overwrite? (y/N) y
(base) ➜  test git:(master) ✗ gpg --decrypt foo.yaml.o
gpg: encrypted with 3072-bit RSA key, ID 29254B12D9D95B7D, created 2021-01-06
      "HZGOOD <805104533@qq.com>"
foo: bar%                                                                                                                                       
(base) ➜  test git:(master) ✗ sops --decrypt foo.enc.yaml                               
foo: bar
```

then sops work
```s
sops -d foo.enc.yaml
foo: bar
```

* Can someone possibly tell me what's going on

**Comment by huang12zheng** [comment]
```sh
gpg --version            
gpg (GnuPG) 2.2.25
libgcrypt 1.8.7
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/huangzheng/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

```
sops --version                 
sops 3.6.1 (latest)
```

**Comment by autrilla** [comment]
Is your GPG key protected by a passphrase?

**Comment by huang12zheng** [comment]
Yes @autrilla

**Comment by tuunit** [comment]
Hi @huang12zheng ,

the problem is that sops is as of now not compatible with GPG 2.1 and above. In GPG 2.1 they introduced a new keyring format in which they merged the public key pairs in one file called pubring.kbx. Sops still expects a secring.gpg file which does not exist anymore.

**Comment by tuunit** [comment]
Hi @huang12zheng,

- SOPS does not support passphrase protected PGP/GPG keys. 
- The secring.gpg is missing because with GPG 2.1 and above the public key pairs are merged into a new format and one file called pubring.kbx which is actually a misleading error message because it is not an issue for SOPS
- After you decrypt once with gpg manually and enter the passphrase. It is stored in during the session by the gpg-agent and therefore no passphrase is necessary for all following sops operations

**Comment by autrilla** [comment]
SOPS does support passphrase protected PGP keys, as long as you're using the GPG 1 keyring format. It's the combination that's not supported..

If you're using the GPG 1 keyring format, we fall back to calling the GPG binary, and that fails if your key is passphrase-protected.

**Comment by huang12zheng** [comment]
I get it. 
I will use GPG1 in the future, 
but it may take a long time.Because I don't have a lot of time
@tuunit The explanation is easy to understand
@autrilla I would close it .

**Comment by apiraino** [comment]
> SOPS does support passphrase protected PGP keys, as long as you're using the GPG 1 keyring format. It's the combination that's not supported..
> 
> If you're using the GPG 1 keyring format, we fall back to calling the GPG binary, and that fails if your key is passphrase-protected.

Aso this [comment](https://github.com/mozilla/sops/issues/567#issuecomment-738066200) possibly related.

@autrilla I came here because I fell in the same trap (tried to use passphrase protected keys generated with GPG v2.2.7). I understand that this is not possible at this time.

Would it be useful for users to mention this in the README? (In case I can help submitting a small patch for that). Perhaps also mentioning if [password protected `age` files are supported](https://github.com/mozilla/sops/issues/567#issuecomment-738066200)?
