### ISSUE TITLE
Removing a sub-part in a document tree

### ISSUE THREAD

**Issue by CyberHippo** [mozilla/sops#798]
Hello,

Is it possible to delete a sub-part in a document tree in the same way that it is possible to [add or edit a subpart](https://github.com/mozilla/sops#set-a-sub-part-in-a-document-tree) using the `--set` option ?
The main goal here would be to remove a key without using an editor and without having to decrypt/encrypt the whole file.

Thank you

**Comment by autrilla** [comment]
This isn’t supported at the moment.

**Comment by CyberHippo** [comment]
@autrilla Thank you for your reply. I understand that the whole file is decrypted / re encrypted during this process. I assume that a new MAC needs to be calculated.

The handy side of using `--set` is that only the `mac`, `lastmodified` sops metadata as well as the edited entry are modified which makes diffs of encrypted files easier to read. Is there a way to delete a key without impacting the `ENC:` metadata of existing keys ? I might be missing something here.

**Comment by autrilla** [comment]
Whether you do it using `--set` or with an editor should have the same result. SOPS will reuse the AES key used to encrypt the file, so the `ENC:` part of unchanged keys should not change. Are you seeing them change? If you do, please come up with a short reproducible example, and add it to this issue, because we would definitely consider that a bug.

**Comment by CyberHippo** [comment]
No sign of a bug. It is entirely related to the logic of our custom script that uses sops. 
Thank you for your answers. I will close this issue.
